apiVersion: v1 
kind: Pod
metadata:
  name: pod-volume
spec: 
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins/jenkins:lts-jdk11
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        # formato unix (Windows)
        # https://cursos.alura.com.br/forum/topico-sugestao-sem-desativar-wsl2-windows-159983
        path: /run/desktop/mnt/host/d/alura/docker/kubernetes-volume
        type: DirectoryOrCreate