apiVersion: apps/v1 # replicasets
kind: Deployment
metadata: 
  name: portal-noticias-deployment
spec:
  template:
    # pod(s) information
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container 
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  # ReplicaSet precisa saber quem ele vai gerenciar
  selector:
    matchLabels:
      app: portal-noticias